export const GET_EVENTS_CREATOR_LIST_SUCCESS = 'GET_EVENTS_LIST_SUCCESS'
export const GET_EVENTS_CREATOR_LIST_ERROR = 'GET_EVENTS_LIST_ERROR'
export const GET_EVENTS_MEMBER_LIST_SUCCESS = 'GET_EVENTS_MEMBER_LIST_SUCCESS'